name: Push to GitHub Pages on push to main
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: sergiojrsc/quickstart@master
        env:
          HUGO_VERSION: 0.88.0
          TARGET_REPO: sergiojrsc/sergiojrsc.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: '-t academic'
          CNAME: sergiojrsc.github.io